---

- hosts: vagrant_dockerhosts
  become: false
  remote_user: "{{ user }}"
  vars:
    swarm_discovery: consul
    swarm_discovery_string: "consul://{{ consul_host }}/swarm"
  roles:
    # - role: base
    - role: docker
  # tasks:
  #   - name: Pull images
  #     become: True
  #     command: >
  #       docker pull {{ item }}:latest
  #     with_items: docker_images

